### ISSUE TITLE
Can't get the brigade gateway url

### ISSUE THREAD

**Issue by wely** [Azure/kubernetes-hackfest#126] opened 2019-11-07 10:18 UTC
I've followed the hackfest guide till https://github.com/Azure/kubernetes-hackfest/blob/master/labs/cicd-automation/brigade/README.md#configure-github-webhook

So far it went well until running this service: "kubectl get service brigade-brigade-github-gw -n brigade"

Returning: "Error from server (NotFound): services "brigade-brigade-github-gw" not found"

**Comment by jschluchter** [comment] 2019-11-15 04:27
Let me get with @chzbrgr71 on this

**Comment by swgriffith** [comment] 2019-11-26 21:09
I just confirmed this in my testing as well. I'll also try to dig into it over the weekend or early next week. Let me know if you hear anything from @chzbrgr71

**Comment by swgriffith** [comment] 2020-01-10 20:06
Finally got around to working through this. The issue is that there were a few changes to the brigade helm chart. It now doesnt implicitly deploy the gateway. You need to specify explicitly via helm params. I addressed along with helm 3 support in the 'helm3-upgrade' branch. PR will be inbound, but you can see the updates in that branch now if you need them.

**Comment by swgriffith** [comment] 2020-01-10 21:22
Addressed by #143

**Comment by jschluchter** [comment] 2020-08-12 14:20
@swgriffith addressed in January

**Closed** 2020-08-12 14:20 UTC
